# to run different optimization algorithms change the 'algorithm' field in global setting
#
# Value             Description
#----------------------------------------------------------------------------------------
# sa                Simulated annealing algorithm
# hbmo              HoneyBee mating optimization algorithm
# hbmo-heft         Gets the number of available instances from HBMO algorithm and then runs the Heterogeneous Earliest Finish Time (HEFT) workflow scheduling algorithm
# heft-before-hbmo  At first, it runs the HEFT and gives the initial solution to the HBMO algorithm
# heft-example      The customized HEFT algorithm for the example in the HEFT paper
#
#
# Key NOTES:
# - All of the algorithm's fitness are based on the HEFT algorithm
#


global:
  algorithm: "hbmo-heft"
  workflow_id: 2
  budget: 1000
  bandwidth: 1
  t_extra: -1
  m_number: 100

sa_algorithm:
  start_temperature: 850
  final_temperature: 0.1
  cooling_factor: 0.8
  force_cooling: false
  equilibrium_point: 10
  number_of_runs: 30

honeybee_algorithm:
  max_speed: 800
  min_speed: 0.1
  force_speed: false
  sMin_division: 100
  sMax_division: 10
  cooling_factor: 0.9
  number_of_threads: 4
  spermatheca_size: 400
# the generation number equals to number of iterations
  generation_number: 150
  neighborhood_ratio: 0.0
  number_of_runs: 30

#antcolony_algorithm: