# to run different optimization algorithms change the 'algorithm' field in global setting
#
#========================================================================================
#============================= ALGORITHM DESCRIPTION TABLE ==============================
#========================================================================================
# Value             Description
#----------------------------------------------------------------------------------------
# sa                Simulated annealing algorithm
# hbmo              HoneyBee mating optimization algorithm with random initial solution
# heft              Heterogeneous Earliest Finish Time algorithm that uses all best instances with a limited number of instances
# hbmo-heft         Gets the number of available instances from HBMO algorithm and then runs the HEFT algorithm
# heft-before-hbmo  At first, it runs the HEFT and gives the initial solution to the HBMO algorithm
# heft-example      The customized HEFT algorithm for the example in the HEFT paper
# pacsa             Parallel Ant Colony leveraged by Simulated Annealing
# pacsa-plus        PACSA algorithm with computed M number
# pso               Particle Swarm Intelligence
#
# Key NOTES:
# - The type of the workflow that the selected algorithm uses to run, is specified through the workflow ID (e.g workflow_id: 3 is the Inspiral 50)
# - All of the algorithm's fitness are based on the HEFT algorithm
# - Number of runs for the heft-before-hbmo algorithm is specified in hbmo section of the config
#


global:
  algorithm: "pacsa-plus"
  workflow_id: 4
  workflow_name: "inspiral_30"
  budget: 10.2
  bandwidth: 39321600
  t_extra: -1
  read_m_number_from_config: no
#  M number: maximum number of instances used during workflow scheduling
  m_number: 0
# id: 1 => normal heft
# id: 2 => cost efficient heft
# id: others => none
  initial_solution_from_heft_id: 0
  use_mysql_to_log: no
  mysql_username: "hessamdb"
  mysql_password: "He$123456789"
  connection_string: "jdbc:mysql://localhost:3306/optdb"

sa_algorithm:
  start_temperature: 850
  final_temperature: 0.01
  cooling_factor: 0.8
  force_cooling: yes
  equilibrium_point: 50
  number_of_runs: 30

honeybee_algorithm:
  max_speed: 800
  min_speed: 0.1
  force_speed: no
  sMin_division: 100
  sMax_division: 10
  cooling_factor: 0.95
  number_of_threads: 4
  spermatheca_size: 400
# the generation number equals to number of iterations
  generation_number: 150
  neighborhood_ratio: 0.0
  number_of_runs: 1
# this toggle is used to switch between single mutation or mutation on every brood
  full_mutation: no

pacsa_algorithm:
  iteration_number: 100
  iteration_number_based: no
  number_of_ants: 16
  number_of_runs: 3
#  cf: cooling factor
  cf_increase_ratio: 1.004
# temp_decrease_ratio: intensification rate
  temp_decrease_ratio: 0.95
  equilibrium_point: 0.99
  evaporation_factor: 0.9
  global_based: yes
  insert_heft_initial_solution: yes

pso_algorithm:
  number_of_runs: 10
  number_of_particles: 500
  maximum_iteration: 1000
  weight: 0.729
  acceleration_coefficient1: 1.494
  acceleration_coefficient2: 1.494