global:
  workflow_id: 2
  budget: 1000
  bandwidth: 1000
  t_extra: -1
  m_number: 100

sa_algorithm:
  start_temperature: 850
  final_temperature: 0.1
  cooling_factor: 0.8
  force_cooling: false
  equilibrium_point: 10

honeybee_algorithm:
  max_speed: 800
  min_speed: 0.1
  force_speed: false
  cooling_factor: 0.9
  number_of_threads: 8
  spermatheca_size: 100
  generation_number: 30
  neighborhood_ratio: 0.1
  number_of_runs: 10

#antcolony_algorithm: