global:
  bandwidth: 1
  t_extera: -1
  m_number: 100

sa_algorithm:
  start_temperature: 850
  final_temperature: 0.1
  cooling_factor: 0.8
  force_cooling: false
  equilibrium_point: 10

#honeybee_algorithm:

#antcolony_algorithm: