# to run different optimization algorithms change the 'algorithm' field in global setting
#
# Value             Description
#----------------------------------------------------------------------------------------
# sa                Simulated annealing algorithm
# hbmo              HoneyBee mating optimization algorithm with random initial solution
# heft              Heterogeneous Earliest Finish Time algorithm that uses all best instances with a limited number of instances
# hbmo-heft         Gets the number of available instances from HBMO algorithm and then runs the HEFT algorithm
# heft-before-hbmo  At first, it runs the HEFT and gives the initial solution to the HBMO algorithm
# heft-example      The customized HEFT algorithm for the example in the HEFT paper
#
#
# Key NOTES:
# - All of the algorithm's fitness are based on the HEFT algorithm
# - Number of runs for the heft-before-hbmo algorithm is specified in hbmo section of the config
#


global:
  algorithm: "hbmo"
  workflow_id: 4
  budget: 1000
  bandwidth: 1
  t_extra: -1
  m_number: 100

sa_algorithm:
  start_temperature: 850
  final_temperature: 0.1
  cooling_factor: 0.8
  force_cooling: no
  equilibrium_point: 10
  number_of_runs: 30

honeybee_algorithm:
  max_speed: 800
  min_speed: 0.1
  force_speed: no
  sMin_division: 100
  sMax_division: 10
  cooling_factor: 0.95
  number_of_threads: 4
  spermatheca_size: 100
# the generation number equals to number of iterations
  generation_number: 2
  neighborhood_ratio: 0.0
  number_of_runs: 1
# this toggle is used to switch between single mutation or mutation on every brood
  full_mutation: no

#antcolony_algorithm: