global:
  bandwidth: 1
  t_extera: -1
  m_number: 100

sa_algorithm:
  start_temperature: 850
  final_temperature: 0.1
  cooling_factor: 0.8
  force_cooling: false
  equilibrium_point: 10

honeybee_algorithm:
  max_speed: 300
  min_speed: 10
  force_speed: true
  cooling_factor: 0.9
  number_of_threads: 8
  spermatheca_size: 30
  generation_number: 20

#antcolony_algorithm: